"""Render Advect's runtime-derived compatibility pages.

The markdown output is the checked-in ``docs/compatibility`` catalog: one
page per provider plus a generated index, all derived from the live frontend
bindings, public extension exports, and primitive registry.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from dataclasses import dataclass
from itertools import pairwise
from pathlib import Path
from typing import cast

from advect.support import support_catalog

_HEADER = (
    "<!-- Generated by `uv run python -m scripts.report_extension_support "
    "--format markdown --output docs/compatibility`; do not edit by hand. -->"
)


@dataclass(frozen=True, slots=True)
class _CuPyEvidence:
    version: str
    cuda_package: str
    cuda_runtime: str
    driver: str
    device: str
    revisions: tuple[str, ...]
    source_revision: str
    artifact_url: str | None = None
    artifact_sha256: str | None = None


_CUPY_EVIDENCE_SOURCE_REVISION = "8112c7add918b31e31985a4d60dc653f18990fdb"
_CUPY_EVIDENCE = (
    _CuPyEvidence(
        version="14.0.1",
        cuda_package="cupy-cuda13x",
        cuda_runtime="13.0",
        driver="610.43.03",
        device="NVIDIA GeForce RTX 4080 SUPER",
        revisions=("2022.12", "2023.12", "2024.12"),
        source_revision=_CUPY_EVIDENCE_SOURCE_REVISION,
    ),
    _CuPyEvidence(
        version="14.1.1",
        cuda_package="cupy-cuda13x",
        cuda_runtime="13.2",
        driver="610.43.03",
        device="NVIDIA GeForce RTX 4080 SUPER",
        revisions=("2022.12", "2023.12", "2024.12"),
        source_revision=_CUPY_EVIDENCE_SOURCE_REVISION,
    ),
)


def _escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _yes_no(value: object) -> str:
    return "yes" if value is True else "no"


def _code(value: object) -> str:
    return f"`{_escape(value)}`"


def _render_primitive_table(rows: list[dict[str, object]]) -> list[str]:
    lines = [
        "| Primitive | JVP | VJP | Abstract | Evaluator |",
        "|---|:---:|:---:|:---:|:---:|",
    ]
    lines.extend(
        "| "
        + " | ".join(
            (
                _code(row["primitive"]),
                _escape(row["jvp"]),
                _escape(row["vjp"]),
                _yes_no(row["abstract"]),
                _yes_no(row["evaluator"]),
            )
        )
        + " |"
        for row in rows
    )
    return lines


def _render_frontend_table(
    rows: list[dict[str, object]],
    *,
    include_entrypoint: bool = False,
    include_backing: bool = False,
    disclose_capabilities: bool = False,
) -> list[str]:
    headers = ["Function"]
    if include_entrypoint:
        headers.append("Advect entry point")
    headers.append("Lowers to")
    if include_backing:
        headers.append("Backed by")
    headers.extend(("Dynamic", "Staged", "Serialized", "JVP", "VJP", "Abstract"))
    alignment = ["---"] * len(headers)
    for name in ("Dynamic", "Staged", "Serialized", "JVP", "VJP", "Abstract"):
        alignment[headers.index(name)] = ":---:"
    lines = [
        f"| {' | '.join(headers)} |",
        f"|{'|'.join(alignment)}|",
    ]
    backing_labels = {
        "advect": "Advect core",
        "array_api": "Array API",
        "composite": "composite",
        "metadata": "metadata",
        "numpy": "NumPy extension",
        "scipy": "SciPy extension",
    }
    for row in rows:
        values = [_code(row["callable"])]
        if include_entrypoint:
            values.append(_code(row["entrypoint"]))
        lowering = str(row["lowering"])
        values.append(
            lowering if lowering in {"adapter", "composite", "metadata"} else _code(lowering)
        )
        if include_backing:
            values.append(backing_labels[str(row["backed_by"])])
        values.extend(
            (
                _yes_no(row["dynamic"]),
                _yes_no(row["staged"]),
                _yes_no(row["serialized"]),
                _escape(row["jvp"]),
                _escape(row["vjp"]),
                _escape(row["abstract"]),
            )
        )
        lines.append(f"| {' | '.join(values)} |")
    if not disclose_capabilities:
        return lines
    backing_class = " compat-has-backing" if include_backing else ""
    return [
        f'<details class="compat-columns{backing_class}">',
        "<summary>capability details</summary>",
        "</details>",
        "",
        *lines,
    ]


def _revision_profiles() -> list[tuple[str, list[dict[str, object]]]]:
    """Collect the official per-revision callable classification."""
    # The classification is not part of the public catalog payload; the
    # renderer reaches for the same internals support_catalog() uses.
    from advect.core._array_api.profiles import (  # noqa: PLC0415
        SUPPORTED_ARRAY_API_VERSIONS,
    )
    from advect.core._array_api.support import build_support_profile  # noqa: PLC0415

    return [
        (
            version,
            cast("list[dict[str, object]]", build_support_profile(version)["callables"]),
        )
        for version in SUPPORTED_ARRAY_API_VERSIONS
    ]


def _normalized_note(note: object) -> str:
    """Strip revision strings so a note rewording alone is not a change."""
    return re.sub(r"20\d\d\.\d\d", "<revision>", str(note))


def _profile_changes(
    previous_rows: list[dict[str, object]],
    rows: list[dict[str, object]],
) -> list[tuple[str, list[tuple[str, object, object]]]]:
    """Collect the material per-callable differences between two revisions."""
    previous = {str(row["path"]): row for row in previous_rows}
    changes = []
    for row in rows:
        old = previous.get(str(row["path"]))
        if old is None:
            continue
        fields: list[tuple[str, object, object]] = [
            (field, old[field], row[field])
            for field in ("signature", "kind", "modes", "complete")
            if old[field] != row[field]
        ]
        if _normalized_note(old["note"]) != _normalized_note(row["note"]):
            fields.append(("note", old["note"], row["note"]))
        if fields:
            changes.append((str(row["path"]), fields))
    return changes


def _render_profile_changes(
    changes: list[tuple[str, list[tuple[str, object, object]]]],
) -> list[str]:
    lines = [
        "| Callable | Change |",
        "|---|---|",
    ]
    for path, fields in changes:
        rendered = "; ".join(f"{field}: {_code(old)} → {_code(new)}" for field, old, new in fields)
        lines.append(f"| {_code(path)} | {rendered} |")
    return lines


def _mode_semantics() -> list[str]:
    return [
        (
            "The mode columns are public support claims: **yes** means the callable's "
            "declared contract is supported end to end in that execution mode "
            "(dynamic tracing, abstract staging, serialized artifacts). Restricted "
            "implementation paths may remain internal, but registration alone does "
            "not promote an additional upstream spelling into this catalog."
        ),
        "",
        (
            "`Abstract=yes` means that a primitive has a standalone abstract rule. A "
            "frontend may still be staged by an explicit method or composite lowering "
            "when its displayed primitive does not."
        ),
    ]


def _cupy_historical_revisions() -> frozenset[str]:
    return frozenset(revision for evidence in _CUPY_EVIDENCE for revision in evidence.revisions)


def _cupy_verified_revisions() -> frozenset[str]:
    return frozenset(
        revision
        for evidence in _CUPY_EVIDENCE
        if evidence.artifact_url is not None and evidence.artifact_sha256 is not None
        for revision in evidence.revisions
    )


def _cupy_evidence_summary() -> str:
    revisions = ", ".join(f"`{revision}`" for revision in sorted(_cupy_historical_revisions()))
    versions = ", ".join(f"`{evidence.version}`" for evidence in _CUPY_EVIDENCE)
    return (
        f"CuPy {versions} has source records for Array API {revisions}; "
        "no published immutable artifact currently verifies release support"
    )


def _render_index(catalog: dict[str, object]) -> str:
    primitives = cast("list[dict[str, object]]", catalog["primitives"])
    extensions = cast("dict[str, dict[str, object]]", catalog["extensions"])
    array_api = cast("list[dict[str, object]]", extensions["array_api"]["functions"])
    numpy = cast("list[dict[str, object]]", extensions["numpy"]["functions"])
    numpy_version = str(extensions["numpy"]["version"])
    scipy = cast("list[dict[str, object]]", extensions["scipy"]["functions"])
    primitive_jvps = sum(row["jvp"] == "yes" for row in primitives)
    primitive_vjps = sum(row["vjp"] in {"direct", "from JVP"} for row in primitives)
    primitive_abstract = sum(row["abstract"] is True for row in primitives)
    primitive_evaluators = sum(row["evaluator"] is True for row in primitives)
    scipy_functions = sum(row["kind"] == "function" for row in scipy)
    scipy_adapters = sum(row["kind"] == "adapter" for row in scipy)

    lines = [
        "# Compatibility",
        "",
        _HEADER,
        "",
        (
            "This catalog is generated from Advect's live frontend bindings, public "
            "extension exports, and primitive registry — it documents what is "
            "qualified, not what happens to work."
        ),
        "",
        *_mode_semantics(),
        "",
        "Per-provider catalogs:",
        "",
        (
            f"- [NumPy](numpy.md) — {len(numpy)} supported callable forms with "
            f"installed NumPy {numpy_version} on the first-class protocol frontend"
        ),
        (
            f"- [Array API](array-api.md) — {len(array_api)} namespace functions "
            "across three qualified standard revisions"
        ),
        (
            f"- [CuPy](cupy.md) — {len(array_api)} Array API namespace functions "
            "in the designated single-device GPU gate; local evidence is not yet published"
        ),
        (
            f"- [SciPy](scipy.md) — {scipy_functions} compatible functions "
            f"and {scipy_adapters} solver adapters behind `advect[scipy]`"
        ),
        ("- [xarray](xarray.md) — the labeled-array pytree contract behind `advect[xarray]`"),
        "",
        "## Measures",
        "",
        "| Measure | Count |",
        "|---|---:|",
        f"| Registered extension primitives | {len(primitives)} |",
        f"| Primitives with JVP | {primitive_jvps} |",
        f"| Primitives with VJP | {primitive_vjps} |",
        f"| Primitives with abstract rule | {primitive_abstract} |",
        f"| Primitives with evaluator | {primitive_evaluators} |",
        f"| Supported Array API functions | {len(array_api)} |",
        f"| Supported NumPy {numpy_version} callable forms | {len(numpy)} |",
        f"| Supported SciPy-compatible functions | {scipy_functions} |",
        f"| SciPy solver adapters | {scipy_adapters} |",
        "",
        "## Primitive capability matrix",
        "",
        (
            "Every frontend row in the per-provider catalogs lowers to a primitive "
            "in this registry; the matrix records which rules each primitive "
            "carries."
        ),
        "",
        *_render_primitive_table(primitives),
    ]
    return "\n".join(lines) + "\n"


def _render_numpy(catalog: dict[str, object]) -> str:
    extensions = cast("dict[str, dict[str, object]]", catalog["extensions"])
    numpy = cast("list[dict[str, object]]", extensions["numpy"]["functions"])
    numpy_array_api = sum(row["backed_by"] == "array_api" for row in numpy)
    extension = cast("dict[str, object]", extensions["numpy"])

    lines = [
        "# NumPy",
        "",
        _HEADER,
        "",
        (
            "NumPy is Advect's first-class frontend, intercepted through NumPy's own "
            "protocols (`__array_ufunc__`, `__array_function__`, and constructor "
            "`like=` dispatch). The qualified range is NumPy 2.0 to 2.4. NumPy "
            "declares the Array API revision implemented by the installed release:"
        ),
        "",
        f"- installed NumPy {extension['version']}: Array API {extension['array_api_version']}",
        "",
        *_mode_semantics(),
        "",
        (
            f"Rows marked **Array API** ({numpy_array_api} of {len(numpy)}) reuse the "
            "same canonical primitive as an Array API binding. They inherit primitive "
            "semantics and derivative rules, not the Array API frontend signature."
        ),
        "",
        (
            "Only supported ufunc methods are listed; "
            f"{extensions['numpy']['unsupported_ufunc_methods']} other method forms "
            "are unqualified. Every row is backed by an executable NumPy case for "
            "each marked lifetime. Reachable handlers without that evidence are omitted. "
            "The nine `numpy.lib.scimath` rows are dynamic-only because their result "
            "dtype can depend on values."
        ),
        "",
        "## Restricted staged forms",
        "",
        (
            "Callable rows are conservative across their executable variants. "
            "`numpy.round` supports staging and serialization when `decimals` is "
            "omitted or zero; nonzero `decimals` is dynamic-only. "
            "`numpy.linalg.eig` and `numpy.linalg.eigvals` support all three "
            "lifetimes for complex input dtypes, while real input dtypes are "
            "dynamic-only."
        ),
        "",
        (
            "`numpy.linspace` is dynamic-only when its endpoints are traced, "
            "including the two-output `retstep=True` form. NumPy accepts "
            "array-valued endpoints, whereas the shared Array API primitive has "
            "static scalar endpoint attributes, so those NumPy calls cannot be "
            "serialized. A constant-only call may be captured as a graph constant; "
            "that is not staged `numpy.linspace` support."
        ),
    ]
    kind_labels = {
        "function": "Functions",
        "ufunc_call": "Ufunc calls",
        "ufunc_method": "Supported ufunc methods",
        "array_method": "ndarray methods",
    }
    for kind, label in kind_labels.items():
        rows = [row for row in numpy if row["kind"] == kind]
        if not rows:
            continue
        lines.extend(
            [
                "",
                f"## {label}",
                "",
                *_render_frontend_table(rows, include_backing=True, disclose_capabilities=True),
            ]
        )
    return "\n".join(lines) + "\n"


def _render_cupy(catalog: dict[str, object]) -> str:
    extensions = cast("dict[str, dict[str, object]]", catalog["extensions"])
    array_api = cast("dict[str, object]", extensions["array_api"])
    functions = cast("list[dict[str, object]]", array_api["functions"])
    profiles = _revision_profiles()
    supported_revisions = {version for version, _ in profiles}
    historical_revisions = _cupy_historical_revisions()
    verified_revisions = _cupy_verified_revisions()
    unknown_revisions = historical_revisions - supported_revisions
    if unknown_revisions:
        message = f"CuPy evidence references unsupported revisions: {sorted(unknown_revisions)}"
        raise RuntimeError(message)

    lines = [
        "# CuPy",
        "",
        _HEADER,
        "",
        (
            "CuPy is Advect's designated single-device GPU provider for the "
            "[Array API frontend](array-api.md). Pass CuPy arrays to a transform and "
            "write numerical code against the traced array's namespace; the built-in "
            "compatibility fallback routes execution through CuPy while derivative seeds, "
            "temporaries, and captured constants stay on the device."
        ),
        "",
        (
            "The configurations below are source records. A clean-worktree local run "
            "covers all three revisions, but no immutable artifact URL is published, so "
            "it does not verify a release CuPy support claim. Run the gate on the final "
            "candidate and retain its complete evidence before publishing one."
        ),
        "",
        (
            "This is an Array API provider contract, not interception of arbitrary "
            "`cupy.*` calls. The function spellings below are methods of the namespace "
            "returned by a traced array."
        ),
        "",
        "## Recorded configurations",
        "",
        (
            "| CuPy | CUDA package | CUDA runtime | NVIDIA driver | Device | "
            "Recorded revisions | Evidence status | Source record |"
        ),
        "|---|---|---|---|---|---|---|---|",
        *(
            f"| `{evidence.version}` | `{evidence.cuda_package}` | "
            f"`{evidence.cuda_runtime}` | `{evidence.driver}` | {evidence.device} | "
            f"{', '.join(f'`{revision}`' for revision in evidence.revisions)} | "
            + (
                f"[verified artifact]({evidence.artifact_url}) "
                f"(`{evidence.artifact_sha256[:12]}`) | "
                if evidence.artifact_url is not None and evidence.artifact_sha256 is not None
                else "unpublished: no immutable artifact URL | "
            )
            + f"[`{evidence.source_revision[:12]}`](https://github.com/yaugenst/advect/commit/"
            f"{evidence.source_revision}) |"
            for evidence in _CUPY_EVIDENCE
        ),
        "",
        "| Array API revision | CuPy status |",
        "|---|---|",
        *(
            f"| `{version}` | "
            + (
                "qualified on the configurations above |"
                if version in verified_revisions
                else "unpublished; attach the final-candidate GPU gate |"
            )
            for version, _ in profiles
        ),
        "",
        (
            "A verified provider qualification would compose one retained "
            "configuration-level artifact with the runtime-derived Array API contract. "
            "It does not require a second CuPy-specific callable inventory."
        ),
        "",
        (
            "The GPU gate below is a representative end-to-end workload rather than one "
            "GPU case per table row. It checks dynamic value/gradient, JVP, VJP, "
            "staged and serialized derivatives, FFT, `linalg.solve`, captured host "
            "constants, copied-field mutation, weak scalars, dtype/device retention, "
            "and cross-provider numerical agreement. The separate donation gate "
            "checks device-memory savings and runtime acceptance."
        ),
        "",
        *_mode_semantics(),
        "",
        "## Functions",
        "",
        (
            f"The {len(functions)} rows below are the Array API namespace surface selected "
            "for CuPy qualification. They are not a release provider pass claim until the "
            "configuration gate has a published immutable artifact and digest."
        ),
        "",
        *_render_frontend_table(functions, disclose_capabilities=True),
        "",
        "## Install",
        "",
        (
            "Install the CuPy wheel family matching the CUDA generation available to "
            "the host. The configurations above used "
            "`uv pip install 'cupy-cuda13x[ctk]==<version>'`; the `ctk` extra made "
            "the toolkit libraries visible inside each isolated environment. Advect "
            "does not select the CUDA package, and no Advect extra or registration "
            "import is required."
        ),
        "",
        "## Qualification gate",
        "",
        (
            "NumPy and `array-api-strict` run in automated CI. CuPy uses the same "
            "scientific provider workload on a CUDA host, followed by the staged "
            "donation acceptance gate. Run this once in each isolated environment "
            "containing the CuPy version being qualified:"
        ),
        "",
        "```bash",
        "uv run pytest \\",
        "  packages/advect/tests/advect_array_api_compat_tests/test_cupy_qualification.py",
        "",
        "for version in 2022.12 2023.12 2024.12; do",
        "  uv run python -m scripts.qualify_array_providers \\",
        '    --array-api-version "$version" ' + "\\",
        "    --providers numpy,array-api-strict,cupy \\",
        '    --output "artifacts/qualification/$version/array-provider-cupy.json"',
        "done",
        "",
        'ADVECT_SOURCE_REVISION="$(git rev-parse HEAD)" ' + "\\",
        "uv run python -m scripts.bench_runtime_memory \\",
        "  --profile cupy-donation \\",
        "  --acceptance \\",
        "  --format json \\",
        '  --output "artifacts/benchmarks/runtime-memory-cupy-donation.json"',
        "```",
        "",
        (
            "The complete procedure, including donation evidence, lives in the "
            "[provider qualification record](https://github.com/yaugenst/advect/blob/main/"
            "design/implementation/array-provider-qualification.md)."
        ),
        "",
        "## Boundaries",
        "",
        "- One process and one device; multi-GPU placement and stream control are not claimed.",
        (
            "- Arrays attached to another autodiff system (`requires_grad=True`) are "
            "rejected instead of composing two derivative tapes."
        ),
        (
            "- Other GPU providers may resolve through the same compatibility path; "
            "that behavior is incidental until the provider passes the same gate."
        ),
    ]
    return "\n".join(lines) + "\n"


def _render_array_api(catalog: dict[str, object]) -> str:
    extensions = cast("dict[str, dict[str, object]]", catalog["extensions"])
    array_api = cast("dict[str, object]", extensions["array_api"])
    functions = cast("list[dict[str, object]]", array_api["functions"])
    profiles = _revision_profiles()
    membership = [(version, {str(row["path"]) for row in rows}) for version, rows in profiles]
    baseline_version, baseline_paths = membership[0]

    def since(path: str) -> str:
        return next(version for version, paths in membership if path in paths)

    bound_paths = {str(row["callable"]) for row in functions}
    newest_rows = profiles[-1][1]
    bounded = [row for row in newest_rows if row["complete"] is not True]

    lines = [
        "# Array API",
        "",
        _HEADER,
        "",
        (
            "Any array whose namespace implements the Array API standard reaches "
            "Advect through `value.__array_namespace__()`; provider-neutral "
            "functions are written against that namespace rather than a specific "
            "package. Advect qualifies the standard revisions "
            f"`{array_api['published_range']['minimum']}` through "
            f"`{array_api['published_range']['maximum']}`; staging can target any "
            "listed revision, and NumPy selects the newest revision implemented by "
            "its installed minor release."
        ),
        "",
        "## Providers",
        "",
        "| Provider | Route into Advect | Status |",
        "|---|---|---|",
        (
            "| NumPy | first-class protocol frontend | qualified — see "
            "[NumPy](numpy.md) for the minor-to-revision mapping |"
        ),
        (
            "| `array-api-strict` | `__array_namespace__()` directly | qualified "
            "for all three revisions below |"
        ),
        (
            "| CuPy | the built-in fallback — install the matching CuPy build "
            "and pass CuPy arrays directly | manual qualification gate; "
            f"{_cupy_evidence_summary()} — see [CuPy](cupy.md) |"
        ),
        "",
        (
            "The fallback handles raw provider arrays at Advect's input boundary; "
            "it does not make an array traceable when its namespace does not "
            "implement the standard."
        ),
        "",
        "## Qualified revisions",
        "",
        "| Revision | Official callables | Complete Advect contracts |",
        "|---|---:|---:|",
    ]
    for version, rows in profiles:
        complete = sum(row["complete"] is True for row in rows)
        lines.append(f"| {_code(version)} | {len(rows)} | {complete} |")
    lines.extend(
        [
            "",
            (
                f"The `{baseline_version}` revision is the baseline; later revisions "
                "extend it. The full baseline surface is listed below, followed by "
                "what each revision adds or changes; the official callables whose "
                "claim stays incomplete are collected at the end."
            ),
            "",
            *_mode_semantics(),
            "",
            f"## Array API {baseline_version} baseline",
            "",
            *_render_frontend_table(
                [row for row in functions if str(row["callable"]) in baseline_paths],
                disclose_capabilities=True,
            ),
        ]
    )
    for (_, previous_rows), (version, rows) in pairwise(profiles):
        known = {str(row["path"]) for row in previous_rows}
        added_paths = {str(row["path"]) for row in rows} - known
        lines.extend(
            [
                "",
                f"## Added in {version}",
                "",
                *_render_frontend_table(
                    [row for row in functions if str(row["callable"]) in added_paths],
                    disclose_capabilities=True,
                ),
            ]
        )
        changes = _profile_changes(previous_rows, rows)
        if changes:
            lines.extend(
                [
                    "",
                    f"## Changed in {version}",
                    "",
                    *_render_profile_changes(changes),
                ]
            )

    def claim(row: dict[str, object]) -> str:
        note = str(row["note"])
        if note == "no executable callable evidence":
            note = "no qualification case exercises it"
        if str(row["path"]) in bound_paths:
            return f"claimed with a boundary: {_escape(note)}"
        return f"none — {_escape(note)}"

    lines.extend(
        [
            "",
            "## Incomplete claims",
            "",
            (
                "This table is the gap between the official-callable and "
                "complete-contract counts above. Advect claims support only on "
                "executable evidence — a qualification case that exercises the "
                "callable end to end. A row without one carries no claim: whatever "
                "a provider path happens to do with it today is incidental, not "
                "contract. A row with a recorded boundary is claimed except for "
                "that boundary."
            ),
            "",
            "| Callable | Kind | Since | Claim |",
            "|---|---|---|---|",
            *(
                f"| {_code(row['path'])} | {_escape(row['kind'])} | "
                f"{_code(since(str(row['path'])))} | {claim(row)} |"
                for row in bounded
            ),
        ]
    )
    return "\n".join(lines) + "\n"


def _render_scipy(catalog: dict[str, object]) -> str:
    extensions = cast("dict[str, dict[str, object]]", catalog["extensions"])
    scipy = cast("dict[str, object]", extensions["scipy"])
    lines = [
        "# SciPy",
        "",
        _HEADER,
        "",
    ]
    if not scipy["available"]:
        lines.append("SciPy is not installed, so this extension is unavailable.")
        return "\n".join(lines) + "\n"
    rows = cast("list[dict[str, object]]", scipy["functions"])
    functions = [row for row in rows if row["kind"] == "function"]
    adapters = [row for row in rows if row["kind"] == "adapter"]
    lines.extend(
        [
            (
                f"SciPy {scipy['version']} compatibility functions are explicit "
                "`advect.scipy` entry points rather than transparent interception of "
                "direct `scipy.*` calls. The module is installed by the "
                "`advect[scipy]` extra, and an artifact that contains one of these "
                "functions needs `import advect.scipy` before "
                "`StagedProgram.from_dict()`."
            ),
            "",
            *_mode_semantics(),
            "",
            (
                "Selection gradients recover the exact winning source and share ties "
                "across window slots. Fast paths cover unique values, low-cardinality "
                "full-footprint plateaus, and common non-flat `structure=` operands; "
                "irregular or high-cardinality ties retain exact candidate routing. "
                "The default `uv run python -m scripts.bench_scipy_runtime --check` "
                "matrix exercises these performance regimes at 256 by 256."
            ),
            "",
            "## Compatible functions",
            "",
            *_render_frontend_table(functions, include_entrypoint=True),
            "",
            "## Solver adapters",
            "",
            (
                "These callback factories are dynamic boundaries for `implicit_root`; "
                "they do not claim that direct SciPy solver calls are traceable."
            ),
            "",
            *_render_frontend_table(adapters, include_entrypoint=True),
        ]
    )
    return "\n".join(lines) + "\n"


def render_pages(catalog: dict[str, object]) -> dict[str, str]:
    """Render the checked-in compatibility pages, keyed by file name."""
    return {
        "index.md": _render_index(catalog),
        "numpy.md": _render_numpy(catalog),
        "array-api.md": _render_array_api(catalog),
        "cupy.md": _render_cupy(catalog),
        "scipy.md": _render_scipy(catalog),
    }


def _human(catalog: dict[str, object]) -> str:
    primitives = cast("list[dict[str, object]]", catalog["primitives"])
    extensions = cast("dict[str, dict[str, object]]", catalog["extensions"])
    lines = [f"Advect extension support catalog v{catalog['schema_version']}"]
    lines.append(f"  primitives: {len(primitives)}")
    for name, extension in extensions.items():
        rows = cast("list[dict[str, object]]", extension["functions"])
        kinds = Counter(str(row["kind"]) for row in rows)
        rendered_kinds = ", ".join(f"{kind}={count}" for kind, count in sorted(kinds.items()))
        lines.append(
            f"  {name} {extension['version']}: {len(rows)} supported"
            + (f" ({rendered_kinds})" if rendered_kinds else "")
        )
    return "\n".join(lines)


def _arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--format", choices=("human", "json", "markdown"), default="human")
    parser.add_argument(
        "--output",
        type=Path,
        help="markdown: the directory receiving one page per catalog document",
    )
    return parser.parse_args()


def main() -> int:
    """Render the live catalog and optionally write it to disk."""
    arguments = _arguments()
    catalog = support_catalog()
    if arguments.format == "markdown":
        if arguments.output is None:
            message = "--format markdown requires --output <directory>"
            raise SystemExit(message)
        arguments.output.mkdir(parents=True, exist_ok=True)
        for name, content in render_pages(catalog).items():
            (arguments.output / name).write_text(content, encoding="utf-8")
            print(arguments.output / name)
        return 0
    if arguments.format == "json":
        rendered = json.dumps(catalog, indent=2, sort_keys=True)
    else:
        rendered = _human(catalog)
    print(rendered)
    if arguments.output is not None:
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(f"{rendered}\n", encoding="utf-8")
    return 0


__all__ = ["main", "render_pages"]
