"""Render Advect's runtime-derived compatibility pages.

The markdown output is the checked-in ``docs/compatibility`` catalog: one
page per provider plus a generated index, all derived from the live frontend
bindings, public extension exports, and primitive registry.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from itertools import pairwise
from pathlib import Path
from typing import cast

from advect.support import support_catalog

_HEADER = (
    "<!-- Generated by `uv run python -m scripts.report_extension_support "
    "--format markdown --output docs/compatibility`; do not edit by hand. -->"
)


def _escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _yes_no(value: object) -> str:
    return "yes" if value is True else "no"


def _code(value: object) -> str:
    return f"`{_escape(value)}`"


def _render_frontend_table(
    rows: list[dict[str, object]],
    *,
    use_entrypoint: bool = False,
) -> list[str]:
    if not all(row["dynamic"] is True for row in rows):
        msg = "Compact compatibility tables require every row to support dynamic transforms"
        raise ValueError(msg)
    lines = [
        "| Function | Stage/save | Differentiate |",
        "|---|:---:|:---:|",
    ]
    for row in rows:
        staged = row["staged"] is True
        serialized = row["serialized"] is True
        if staged == serialized:
            stage_save = _yes_no(staged)
        else:
            stage_save = "stage only" if staged else "save only"

        jvp = str(row["jvp"])
        vjp = str(row["vjp"])
        has_jvp = jvp in {"yes", "composite"}
        has_vjp = vjp in {"direct", "from JVP", "composite"}
        if jvp == vjp == "n/a":
            differentiate = "n/a"
        elif has_jvp and has_vjp:
            differentiate = "yes"
        elif has_jvp:
            differentiate = "forward only"
        elif has_vjp:
            differentiate = "reverse only"
        else:
            differentiate = "no"

        name = row["entrypoint"] if use_entrypoint else row["callable"]
        lines.append(f"| {_code(name)} | {stage_save} | {differentiate} |")
    return lines


def _revision_profiles() -> list[tuple[str, list[dict[str, object]]]]:
    """Collect the official per-revision callable classification."""
    # The classification is not part of the public catalog payload; the
    # renderer reaches for the same internals support_catalog() uses.
    from advect.core._array_api.profiles import (  # noqa: PLC0415
        SUPPORTED_ARRAY_API_VERSIONS,
    )
    from advect.core._array_api.support import build_support_profile  # noqa: PLC0415

    return [
        (
            version,
            cast("list[dict[str, object]]", build_support_profile(version)["callables"]),
        )
        for version in SUPPORTED_ARRAY_API_VERSIONS
    ]


def _normalized_note(note: object) -> str:
    """Strip revision strings so a note rewording alone is not a change."""
    return re.sub(r"20\d\d\.\d\d", "<revision>", str(note))


def _profile_changes(
    previous_rows: list[dict[str, object]],
    rows: list[dict[str, object]],
) -> list[tuple[str, list[tuple[str, object, object]]]]:
    """Collect the material per-callable differences between two revisions."""
    previous = {str(row["path"]): row for row in previous_rows}
    changes = []
    for row in rows:
        old = previous.get(str(row["path"]))
        if old is None:
            continue
        fields: list[tuple[str, object, object]] = [
            (field, old[field], row[field])
            for field in ("signature", "kind", "modes", "complete")
            if old[field] != row[field]
        ]
        if _normalized_note(old["note"]) != _normalized_note(row["note"]):
            fields.append(("note", old["note"], row["note"]))
        if fields:
            changes.append((str(row["path"]), fields))
    return changes


def _render_profile_changes(
    changes: list[tuple[str, list[tuple[str, object, object]]]],
) -> list[str]:
    lines = [
        "| Callable | Change |",
        "|---|---|",
    ]
    for path, fields in changes:
        rendered = "; ".join(f"{field}: {_code(old)} → {_code(new)}" for field, old, new in fields)
        lines.append(f"| {_code(path)} | {rendered} |")
    return lines


def _table_semantics() -> list[str]:
    return [
        (
            "Every listed function works in dynamic transforms. **Stage/save** says "
            "whether the same call can appear in a staged and serialized program. "
            "**Differentiate** reports user-visible derivative support. **No** means "
            "no derivative rule is available; **n/a** marks a structural or "
            "mathematically nondifferentiable operation."
        ),
    ]


def _render_index(catalog: dict[str, object]) -> str:
    extensions = cast("dict[str, dict[str, object]]", catalog["extensions"])
    array_api = cast("list[dict[str, object]]", extensions["array_api"]["functions"])
    numpy = cast("list[dict[str, object]]", extensions["numpy"]["functions"])
    numpy_version = str(extensions["numpy"]["version"])
    scipy = cast("list[dict[str, object]]", extensions["scipy"]["functions"])
    scipy_functions = sum(row["kind"] == "function" for row in scipy)
    scipy_adapters = sum(row["kind"] == "adapter" for row in scipy)

    lines = [
        "# Compatibility",
        "",
        _HEADER,
        "",
        (
            "The NumPy, Array API, and SciPy tables are generated from Advect's "
            "executable support declarations. The CuPy and xarray pages state their "
            "integration boundaries separately."
        ),
        "",
        *_table_semantics(),
        "",
        "| Integration | Contract |",
        "|---|---|",
        (
            f"| [NumPy](numpy.md) | {len(numpy)} callable forms; NumPy 2.0-2.5 "
            f"({numpy_version} in this build) |"
        ),
        (
            f"| [Array API](array-api.md) | {len(array_api)} namespace functions "
            "across revisions 2022.12-2024.12 |"
        ),
        "| [CuPy](cupy.md) | Array API provider path; pre-release qualification only |",
        (
            f"| [SciPy](scipy.md) | {scipy_functions} functions and {scipy_adapters} "
            "solver adapters behind `advect[scipy]` |"
        ),
        "| [xarray](xarray.md) | Dynamic labeled-container pytrees behind `advect[xarray]` |",
        "",
        (
            "For the raw operation and rule data, use "
            "[`advect.support_catalog()`](../api/support.md)."
        ),
    ]
    return "\n".join(lines) + "\n"


def _render_numpy(catalog: dict[str, object]) -> str:
    extensions = cast("dict[str, dict[str, object]]", catalog["extensions"])
    numpy = cast("list[dict[str, object]]", extensions["numpy"]["functions"])
    extension = cast("dict[str, object]", extensions["numpy"])

    lines = [
        "# NumPy",
        "",
        _HEADER,
        "",
        (
            "NumPy is Advect's first-class frontend, intercepted through NumPy's own "
            "protocols (`__array_ufunc__`, `__array_function__`, and constructor "
            "`like=` dispatch). The qualified range is NumPy 2.0-2.5. This build uses "
            f"NumPy {extension['version']} against Advect's Array API "
            f"{extension['array_api_version']} target. Only the forms listed below "
            "are qualified."
        ),
        "",
        *_table_semantics(),
        (
            "The nine `numpy.lib.scimath` rows are dynamic-only because their result "
            "dtype can depend on values."
        ),
        "",
        "## Limits",
        "",
        (
            "Callable rows are conservative across their executable variants. "
            "`numpy.round` supports staging and serialization when `decimals` is "
            "omitted or zero; nonzero `decimals` is dynamic-only. "
            "`numpy.linalg.eig` and `numpy.linalg.eigvals` support all three "
            "lifetimes for complex input dtypes, while real input dtypes are "
            "dynamic-only."
        ),
        "",
        (
            "`numpy.linspace` is dynamic-only when its endpoints are traced, "
            "including the two-output `retstep=True` form. NumPy accepts "
            "array-valued endpoints, whereas the shared Array API primitive has "
            "static scalar endpoint attributes, so those NumPy calls cannot be "
            "serialized. A constant-only call may be captured as a graph constant; "
            "that is not staged `numpy.linspace` support."
        ),
    ]
    kind_labels = {
        "function": "Functions",
        "ufunc_call": "Ufunc calls",
        "ufunc_method": "Supported ufunc methods",
        "array_method": "ndarray methods",
    }
    for kind, label in kind_labels.items():
        rows = [row for row in numpy if row["kind"] == kind]
        if not rows:
            continue
        lines.extend(
            [
                "",
                f"## {label}",
                "",
                *_render_frontend_table(rows),
            ]
        )
    return "\n".join(lines) + "\n"


def _render_cupy(_catalog: dict[str, object]) -> str:
    lines = [
        "# CuPy",
        "",
        _HEADER,
        "",
        (
            "CuPy uses Advect's single-device [Array API](array-api.md) path. Pass "
            "CuPy arrays to a transform and write numerical code against the namespace "
            "returned by `x.__array_namespace__()`; this does not intercept arbitrary "
            "`cupy.*` calls."
        ),
        "",
        (
            "CuPy support is not yet a release claim. The generated "
            "[Array API table](array-api.md) is the candidate callable set, not evidence "
            "that a final CuPy release gate has passed; Advect does not maintain a "
            "duplicate CuPy inventory."
        ),
        "",
        "## Install",
        "",
        (
            "Install the CuPy wheel family matching the CUDA generation available to "
            "the host. Advect does not select the CUDA package, and no Advect extra or "
            "registration import is required."
        ),
        "",
        "## Boundaries",
        "",
        "- One process and one device; multi-GPU placement and stream control are not claimed.",
        (
            "- Arrays attached to another autodiff system (`requires_grad=True`) are "
            "rejected instead of composing two derivative tapes."
        ),
    ]
    return "\n".join(lines) + "\n"


def _render_array_api(catalog: dict[str, object]) -> str:
    extensions = cast("dict[str, dict[str, object]]", catalog["extensions"])
    array_api = cast("dict[str, object]", extensions["array_api"])
    functions = cast("list[dict[str, object]]", array_api["functions"])
    profiles = _revision_profiles()
    membership = [(version, {str(row["path"]) for row in rows}) for version, rows in profiles]
    baseline_version, baseline_paths = membership[0]

    def since(path: str) -> str:
        return next(version for version, paths in membership if path in paths)

    bound_paths = {str(row["callable"]) for row in functions}
    newest_rows = profiles[-1][1]
    bounded = [row for row in newest_rows if row["complete"] is not True]

    lines = [
        "# Array API",
        "",
        _HEADER,
        "",
        (
            "Any array whose namespace implements the Array API standard reaches "
            "Advect through `value.__array_namespace__()`; provider-neutral "
            "functions are written against that namespace rather than a specific "
            "package. Advect qualifies the standard revisions "
            f"`{array_api['published_range']['minimum']}` through "
            f"`{array_api['published_range']['maximum']}`; staging can target any "
            "listed revision, and NumPy selects the newest revision implemented by "
            "its installed minor release."
        ),
        "",
        "## Providers",
        "",
        "| Provider | Status |",
        "|---|---|",
        (
            "| NumPy | Qualified through its first-class frontend; see "
            "[NumPy](numpy.md) for the minor-to-revision mapping |"
        ),
        (
            "| `array-api-strict` | Qualified through `__array_namespace__()` for all "
            "three revisions below |"
        ),
        (
            "| CuPy | Built-in compatibility path; not yet a release support claim. "
            "See [CuPy](cupy.md) |"
        ),
        "",
        (
            "The fallback handles raw provider arrays at Advect's input boundary; "
            "it does not make an array traceable when its namespace does not "
            "implement the standard."
        ),
        "",
        "## Qualified revisions",
        "",
        "| Revision | Official callables | Complete Advect contracts |",
        "|---|---:|---:|",
    ]
    for version, rows in profiles:
        complete = sum(row["complete"] is True for row in rows)
        lines.append(f"| {_code(version)} | {len(rows)} | {complete} |")
    lines.extend(
        [
            "",
            (
                f"The `{baseline_version}` revision is the baseline; later revisions "
                "extend it. Its callable set appears below, followed by additions, "
                "changes, and the few official functions with a remaining boundary."
            ),
            "",
            *_table_semantics(),
            "",
            f"## Array API {baseline_version} baseline",
            "",
            *_render_frontend_table(
                [row for row in functions if str(row["callable"]) in baseline_paths],
            ),
        ]
    )
    for (_, previous_rows), (version, rows) in pairwise(profiles):
        known = {str(row["path"]) for row in previous_rows}
        added_paths = {str(row["path"]) for row in rows} - known
        lines.extend(
            [
                "",
                f"## Added in {version}",
                "",
                *_render_frontend_table(
                    [row for row in functions if str(row["callable"]) in added_paths],
                ),
            ]
        )
        changes = _profile_changes(previous_rows, rows)
        if changes:
            lines.extend(
                [
                    "",
                    f"## Changed in {version}",
                    "",
                    *_render_profile_changes(changes),
                ]
            )

    def claim(row: dict[str, object]) -> str:
        note = str(row["note"])
        if note == "no executable callable evidence":
            note = "no qualification case exercises it"
        if str(row["path"]) in bound_paths:
            return _escape(note)
        return f"unsupported — {_escape(note)}"

    lines.extend(
        [
            "",
            "## Limits",
            "",
            (
                "These official functions are either unsupported or supported with "
                "the boundary shown. Unlisted provider behavior is not a public claim."
            ),
            "",
            "| Callable | Since | Boundary |",
            "|---|---|---|",
            *(
                f"| {_code(row['path'])} | {_code(since(str(row['path'])))} | {claim(row)} |"
                for row in bounded
            ),
        ]
    )
    return "\n".join(lines) + "\n"


def _render_scipy(catalog: dict[str, object]) -> str:
    extensions = cast("dict[str, dict[str, object]]", catalog["extensions"])
    scipy = cast("dict[str, object]", extensions["scipy"])
    lines = [
        "# SciPy",
        "",
        _HEADER,
        "",
    ]
    if not scipy["available"]:
        lines.append("SciPy is not installed, so this extension is unavailable.")
        return "\n".join(lines) + "\n"
    rows = cast("list[dict[str, object]]", scipy["functions"])
    functions = [row for row in rows if row["kind"] == "function"]
    adapters = [row for row in rows if row["kind"] == "adapter"]
    lines.extend(
        [
            (
                f"SciPy {scipy['version']} compatibility functions are explicit "
                "`advect.scipy` entry points rather than transparent interception of "
                "direct `scipy.*` calls. The module is installed by the "
                "`advect[scipy]` extra, and an artifact that contains one of these "
                "functions needs `import advect.scipy` before "
                "`StagedProgram.from_dict()`."
            ),
            "",
            *_table_semantics(),
            "",
            "## Compatible functions",
            "",
            *_render_frontend_table(functions, use_entrypoint=True),
            "",
            "## Solver adapters",
            "",
            (
                "These callback factories are dynamic boundaries for `implicit_root`; "
                "they do not claim that direct SciPy solver calls are traceable."
            ),
            "",
            *_render_frontend_table(adapters, use_entrypoint=True),
        ]
    )
    return "\n".join(lines) + "\n"


def render_pages(catalog: dict[str, object]) -> dict[str, str]:
    """Render the checked-in compatibility pages, keyed by file name."""
    return {
        "index.md": _render_index(catalog),
        "numpy.md": _render_numpy(catalog),
        "array-api.md": _render_array_api(catalog),
        "cupy.md": _render_cupy(catalog),
        "scipy.md": _render_scipy(catalog),
    }


def _human(catalog: dict[str, object]) -> str:
    primitives = cast("list[dict[str, object]]", catalog["primitives"])
    extensions = cast("dict[str, dict[str, object]]", catalog["extensions"])
    lines = [f"Advect extension support catalog v{catalog['schema_version']}"]
    lines.append(f"  primitives: {len(primitives)}")
    for name, extension in extensions.items():
        rows = cast("list[dict[str, object]]", extension["functions"])
        kinds = Counter(str(row["kind"]) for row in rows)
        rendered_kinds = ", ".join(f"{kind}={count}" for kind, count in sorted(kinds.items()))
        lines.append(
            f"  {name} {extension['version']}: {len(rows)} supported"
            + (f" ({rendered_kinds})" if rendered_kinds else "")
        )
    return "\n".join(lines)


def _arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--format", choices=("human", "json", "markdown"), default="human")
    parser.add_argument(
        "--output",
        type=Path,
        help="markdown: the directory receiving one page per catalog document",
    )
    return parser.parse_args()


def main() -> int:
    """Render the live catalog and optionally write it to disk."""
    arguments = _arguments()
    catalog = support_catalog()
    if arguments.format == "markdown":
        if arguments.output is None:
            message = "--format markdown requires --output <directory>"
            raise SystemExit(message)
        arguments.output.mkdir(parents=True, exist_ok=True)
        for name, content in render_pages(catalog).items():
            (arguments.output / name).write_text(content, encoding="utf-8")
            print(arguments.output / name)
        return 0
    if arguments.format == "json":
        rendered = json.dumps(catalog, indent=2, sort_keys=True)
    else:
        rendered = _human(catalog)
    print(rendered)
    if arguments.output is not None:
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(f"{rendered}\n", encoding="utf-8")
    return 0


__all__ = ["main", "render_pages"]
