"""Ufuncs admitted by the concrete NumPy frontend."""

from __future__ import annotations

import numpy as np

_SUPPORTED_UFUNC_NAMES = (
    "ufunc",
    "add",
    "subtract",
    "multiply",
    "divide",
    "true_divide",
    "floor_divide",
    "remainder",
    "fmod",
    "float_power",
    "hypot",
    "copysign",
    "arctan2",
    "nextafter",
    "negative",
    "positive",
    "conjugate",
    "absolute",
    "fabs",
    "floor",
    "ceil",
    "trunc",
    "rint",
    "sign",
    "signbit",
    "spacing",
    "reciprocal",
    "sin",
    "cos",
    "tan",
    "arcsin",
    "arccos",
    "arctan",
    "arcsinh",
    "arccosh",
    "arctanh",
    "sinh",
    "cosh",
    "exp",
    "exp2",
    "expm1",
    "cbrt",
    "log",
    "log1p",
    "log2",
    "log10",
    "logaddexp",
    "logaddexp2",
    "deg2rad",
    "radians",
    "rad2deg",
    "degrees",
    "tanh",
    "sqrt",
    "square",
    "power",
    "equal",
    "not_equal",
    "isnan",
    "isfinite",
    "isinf",
    "less",
    "less_equal",
    "greater",
    "greater_equal",
    "heaviside",
    "invert",
    "logical_not",
    "logical_and",
    "logical_or",
    "logical_xor",
    "bitwise_and",
    "bitwise_or",
    "bitwise_xor",
    "maximum",
    "minimum",
    "fmax",
    "fmin",
    "ldexp",
    "matmul",
    "matvec",
    "vecmat",
    "vecdot",
    "divmod",
    "frexp",
    "modf",
)
_SUPPORTED_UFUNCS: frozenset[np.ufunc] = frozenset(
    ufunc
    for name in _SUPPORTED_UFUNC_NAMES
    if isinstance((ufunc := getattr(np, name, None)), np.ufunc)
)


__all__ = ["_SUPPORTED_UFUNCS"]
